/**
 * Данные страницы категории коллекций (Lorenz)
 */
export const categoryPage = {
    pageTitle: 'Коллекции',
    collections: [
        {
            id: 1,
            img: '/images/category/1.jpg',
            alt: 'collection',
            subtitle: 'SWISS MADE',
            title: 'HYDRO-SUB',
            slugs: { type: 'watches', collectionSlug: 'hydro-sub' },
        },
        {
            id: 2,
            img: '/images/category/2.jpg',
            alt: 'collection',
            subtitle: 'SWISS MADE',
            title: 'SPORTING CLUB',
            slugs: { type: 'watches', collectionSlug: 'sporting-club' },
        },
        {
            id: 3,
            img: '/images/category/3.jpg',
            alt: 'collection',
            subtitle: 'SWISS MADE',
            title: 'ACAPULCO',
            slugs: { type: 'watches', collectionSlug: 'acapulco' },
        },
        {
            id: 4,
            img: '/images/category/4.jpg',
            alt: 'collection',
            subtitle: 'SWISS MADE',
            title: 'CONNERY',
            slugs: { type: 'watches', collectionSlug: 'connery' },
        },
        {
            id: 5,
            img: '/images/category/5.jpg',
            alt: 'collection',
            subtitle: 'SWISS MADE',
            title: 'OLIVIER',
            slugs: { type: 'watches', collectionSlug: 'olivier' },
        },
        {
            id: 6,
            img: '/images/category/1.jpg',
            alt: 'collection',
            subtitle: 'SWISS MADE',
            title: 'CALIFORNIA',
            slugs: { type: 'watches', collectionSlug: 'california' },
        },
        {
            id: 7,
            img: '/images/category/2.jpg',
            alt: 'collection',
            subtitle: 'SWISS MADE',
            title: 'BEL AMI',
            slugs: { type: 'watches', collectionSlug: 'bel-ami' },
        },
        {
            id: 8,
            img: '/images/category/3.jpg',
            alt: 'collection',
            subtitle: 'DIVER',
            title: 'DI300',
            slugs: { type: 'watches', collectionSlug: 'di300' },
        },
        {
            id: 9,
            img: '/images/category/4.jpg',
            alt: 'collection',
            subtitle: 'DIVER',
            title: 'FULL TITANIUM',
            slugs: { type: 'watches', collectionSlug: 'full-titanium' },
        },
        {
            id: 10,
            img: '/images/category/5.jpg',
            alt: 'collection',
            subtitle: 'DIVER',
            title: 'AQUITANIA',
            slugs: { type: 'watches', collectionSlug: 'aquitania' },
        },
        {
            id: 11,
            img: '/images/category/1.jpg',
            alt: 'collection',
            subtitle: 'DIVER',
            title: 'OCEAN CLUB',
            slugs: { type: 'watches', collectionSlug: 'ocean-club' },
        },
        {
            id: 12,
            img: '/images/category/2.jpg',
            alt: 'collection',
            subtitle: 'DIVER',
            title: 'SHARK',
            slugs: { type: 'watches', collectionSlug: 'shark' },
        },
        {
            id: 13,
            img: '/images/category/3.jpg',
            alt: 'collection',
            subtitle: 'DIVER',
            title: 'GMT',
            slugs: { type: 'watches', collectionSlug: 'gmt' },
        },
        {
            id: 14,
            img: '/images/category/4.jpg',
            alt: 'collection',
            subtitle: 'DIVER',
            title: 'TAKO',
            slugs: { type: 'watches', collectionSlug: 'tako' },
        },
        {
            id: 15,
            img: '/images/category/5.jpg',
            alt: 'collection',
            subtitle: 'CLASSICI',
            title: 'GINEVRA',
            slugs: { type: 'watches', collectionSlug: 'ginevra' },
        },
        {
            id: 16,
            img: '/images/category/1.jpg',
            alt: 'collection',
            subtitle: 'CLASSICI',
            title: 'CHARLESTON',
            slugs: { type: 'watches', collectionSlug: 'charleston' },
        },
        {
            id: 17,
            img: '/images/category/2.jpg',
            alt: 'collection',
            subtitle: 'GRANPREMIO',
            title: 'CARBON',
            slugs: { type: 'watches', collectionSlug: 'carbon' },
        },
        {
            id: 18,
            img: '/images/category/3.jpg',
            alt: 'collection',
            subtitle: 'GRANPREMIO',
            title: 'LIMITED',
            slugs: { type: 'watches', collectionSlug: 'limited' },
        },
        {
            id: 19,
            img: '/images/category/4.jpg',
            alt: 'collection',
            subtitle: 'GRANPREMIO',
            title: 'SPORT',
            slugs: { type: 'watches', collectionSlug: 'sport' },
        },
        {
            id: 20,
            img: '/images/category/5.jpg',
            alt: 'collection',
            subtitle: 'DIVA',
            title: 'DIVA DONNA',
            slugs: { type: 'watches', collectionSlug: 'diva-donna' },
        },
        {
            id: 21,
            img: '/images/category/1.jpg',
            alt: 'collection',
            subtitle: 'EASY TIME',
            title: 'RETRÒ',
            slugs: { type: 'watches', collectionSlug: 'retro' },
        },
        {
            id: 22,
            img: '/images/category/2.jpg',
            alt: 'collection',
            subtitle: 'EASY TIME',
            title: 'SPORT',
            slugs: { type: 'watches', collectionSlug: 'easy-time-sport' },
        },
        {
            id: 23,
            img: '/images/category/3.jpg',
            alt: 'collection',
            subtitle: 'DESIGN',
            title: 'STATIC',
            slugs: { type: 'watches', collectionSlug: 'static' },
        },
    ],
}
